/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as RepairsRouteImport } from './routes/repairs'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as TenanciesRouteImport } from './routes/tenancies'
import { Route as ApiAccountEnterRouteImport } from './routes/api/account/enter'
import { Route as ApiAccountOpenRouteImport } from './routes/api/account/open'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairsRoute = RepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const TenanciesRoute = TenanciesRouteImport.update({
  id: '/tenancies',
  path: '/tenancies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountEnterRoute = ApiAccountEnterRouteImport.update({
  id: '/api/account/enter',
  path: '/api/account/enter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountOpenRoute = ApiAccountOpenRouteImport.update({
  id: '/api/account/open',
  path: '/api/account/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/guide': typeof GuideRoute
  '/income': typeof IncomeRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/properties': typeof PropertiesRoute
  '/repairs': typeof RepairsRoute
  '/security': typeof SecurityRoute
  '/tenancies': typeof TenanciesRoute
  '/api/account/enter': typeof ApiAccountEnterRoute
  '/api/account/open': typeof ApiAccountOpenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/guide': typeof GuideRoute
  '/income': typeof IncomeRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/properties': typeof PropertiesRoute
  '/repairs': typeof RepairsRoute
  '/security': typeof SecurityRoute
  '/tenancies': typeof TenanciesRoute
  '/api/account/enter': typeof ApiAccountEnterRoute
  '/api/account/open': typeof ApiAccountOpenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/guide': typeof GuideRoute
  '/income': typeof IncomeRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/properties': typeof PropertiesRoute
  '/repairs': typeof RepairsRoute
  '/security': typeof SecurityRoute
  '/tenancies': typeof TenanciesRoute
  '/api/account/enter': typeof ApiAccountEnterRoute
  '/api/account/open': typeof ApiAccountOpenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/guide'
    | '/income'
    | '/ledger'
    | '/login'
    | '/properties'
    | '/repairs'
    | '/security'
    | '/tenancies'
    | '/api/account/enter'
    | '/api/account/open'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desk'
    | '/guide'
    | '/income'
    | '/ledger'
    | '/login'
    | '/properties'
    | '/repairs'
    | '/security'
    | '/tenancies'
    | '/api/account/enter'
    | '/api/account/open'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/guide'
    | '/income'
    | '/ledger'
    | '/login'
    | '/properties'
    | '/repairs'
    | '/security'
    | '/tenancies'
    | '/api/account/enter'
    | '/api/account/open'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRoute
  GuideRoute: typeof GuideRoute
  IncomeRoute: typeof IncomeRoute
  LedgerRoute: typeof LedgerRoute
  LoginRoute: typeof LoginRoute
  PropertiesRoute: typeof PropertiesRoute
  RepairsRoute: typeof RepairsRoute
  SecurityRoute: typeof SecurityRoute
  TenanciesRoute: typeof TenanciesRoute
  ApiAccountEnterRoute: typeof ApiAccountEnterRoute
  ApiAccountOpenRoute: typeof ApiAccountOpenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repairs': {
      id: '/repairs'
      path: '/repairs'
      fullPath: '/repairs'
      preLoaderRoute: typeof RepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenancies': {
      id: '/tenancies'
      path: '/tenancies'
      fullPath: '/tenancies'
      preLoaderRoute: typeof TenanciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/enter': {
      id: '/api/account/enter'
      path: '/api/account/enter'
      fullPath: '/api/account/enter'
      preLoaderRoute: typeof ApiAccountEnterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/open': {
      id: '/api/account/open'
      path: '/api/account/open'
      fullPath: '/api/account/open'
      preLoaderRoute: typeof ApiAccountOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRoute,
  GuideRoute: GuideRoute,
  IncomeRoute: IncomeRoute,
  LedgerRoute: LedgerRoute,
  LoginRoute: LoginRoute,
  PropertiesRoute: PropertiesRoute,
  RepairsRoute: RepairsRoute,
  SecurityRoute: SecurityRoute,
  TenanciesRoute: TenanciesRoute,
  ApiAccountEnterRoute: ApiAccountEnterRoute,
  ApiAccountOpenRoute: ApiAccountOpenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
